### ISSUE TITLE
Cannot access server

### ISSUE THREAD

**Issue by sharonlevy** [dmis-lab/covidAsk#3]
Hi,

I am unable to make requests to your server (https://covidask.korea.ac.kr). I also cannot host my own covidAsk (it is timing out on the query). Is there some way to get your server back up?

Thanks.

**Comment by jhyuklee** [comment]
Hi I'm sorry for the inconvenience. We are on our way to solve the problem.

**Comment by jhyuklee** [comment]
The server was down for a moment. Please try again. Thanks!
