### ISSUE TITLE
Annotated Q-A pairs ?

### ISSUE THREAD

**Issue by shamanez** [dmis-lab/covidAsk#4]
Hi, where I can find the annotated QA pairs?

**Comment by jhyuklee** [comment]
See here: https://github.com/dmis-lab/covidAsk#data

**Comment by shamanez** [comment]
Thank you very much. One more thing, the questions consist of multiple answers. Is there a selection mechanism to select an answer?

**Comment by shamanez** [comment]
@jhyuklee

**Comment by jhyuklee** [comment]
What do you mean by a selection mechanism? Annotation criterion? or evaluation criterion?
