### ISSUE TITLE
ConnectionRefusedError: Not able to run the sample code from Colab?

### ISSUE THREAD

**Issue by allaabdella2** [dmis-lab/covidAsk#5]
Hi, 

I tried the sample code and it gives this error. 
Thanks,
--------------------------------------------------------------------------------------------
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f76f7bd45c0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
MaxRetryError: HTTPSConnectionPool(host='covidask.korea.ac.kr', port=443): Max retries exceeded with url: /api?query=Is+there+concrete+evidence+for+the+presence+of+asymptomatic+transmissions%3F&strat=dense_first (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f76f7bd45c0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='covidask.korea.ac.kr', port=443): Max retries exceeded with url: /api?query=Is+there+concrete+evidence+for+the+presence+of+asymptomatic+transmissions%3F&strat=dense_first (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f76f7bd45c0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by jhyuklee** [comment]
The server was down for a moment. Please try again. Thanks!
