### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by HariAakash646** [dmis-lab/covidAsk#8]
The server is currently down and I was wondering when will it be up again?
And I also wanted to know about the permissions required to host the server...

**Comment by jhyuklee** [comment]
Hi, we are currently working on to migrate our server to a different host machine. It will take at least one week. I think you have already opened issues regarding the permissions, so it would be better to discuss that in that thread.

**Comment by HariAakash646** [comment]
Oh ok let me close this issue now...
Will the server be up within the end of this month?

**Comment by jhyuklee** [comment]
Hopefully yes. Will leave comments here.

**Comment by HariAakash646** [comment]
Hey is the server back on @jhyuklee

**Comment by jhyuklee** [comment]
Sorry for the delay, the server is up again.
